version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - main
        ports:
            - 80:80
        volumes:
            - ./main/media:/nginx/media

    main:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash -c "sleep 2 &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn config.wsgi -c ./config/gunicorn.py"
        volumes:
            - ./main/media:/main/media
        depends_on:
            - db
        environment:
            DEBUG: 'False'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres


