# Generated by Django 3.0.8 on 2020-11-18 18:21

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605723706', null=True, verbose_name='id для генерации в шаблоне'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to=apps.core.models.image_upload_path, verbose_name='Основное фото', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image_mouseover',
            field=models.ImageField(height_field='image_height', upload_to=apps.core.models.image_upload_path, verbose_name='Фото при наведении мыши', width_field='image_width'),
        ),
    ]
