# Generated by Django 3.0.8 on 2020-11-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201118_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605724488', null=True, verbose_name='id для генерации в шаблоне'),
        ),
    ]
