# Generated by Django 3.0.8 on 2020-11-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201118_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605724631', null=True, verbose_name='id для генерации в шаблоне'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Старая цена (будет зачеркнута)'),
        ),
    ]
