# Generated by Django 3.0.8 on 2020-11-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201118_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavbarModel',
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605781791', null=True, verbose_name='id для генерации в шаблоне'),
        ),
    ]
