# Generated by Django 3.0.8 on 2020-11-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201119_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width', models.PositiveSmallIntegerField(default=1680, verbose_name='Ширина фото')),
                ('image_height', models.PositiveSmallIntegerField(default=945, verbose_name='Высота фото')),
                ('image', models.ImageField(height_field='image_height', upload_to='background/', verbose_name='Фото верхнего фона', width_field='image_width')),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605782988', null=True, verbose_name='id для генерации в шаблоне'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image_height',
            field=models.PositiveSmallIntegerField(default=561, verbose_name='Высота фото'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='image_width',
            field=models.PositiveSmallIntegerField(default=634, verbose_name='Ширина фото'),
        ),
    ]
