# Generated by Django 3.0.8 on 2020-11-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201119_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block3Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width', models.PositiveSmallIntegerField(default=1680, verbose_name='Ширина фото')),
                ('image_height', models.PositiveSmallIntegerField(default=2519, verbose_name='Высота фото')),
                ('first_image', models.ImageField(height_field='image_height', upload_to='block3_images/', verbose_name='Первое фото третьего блока', width_field='image_width')),
                ('second_image', models.ImageField(height_field='image_height', upload_to='block3_images/', verbose_name='Второе фото третьего блока', width_field='image_width')),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605783946', null=True, verbose_name='id для генерации в шаблоне'),
        ),
        migrations.AlterField(
            model_name='topbackgroundimage',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='top_background/', verbose_name='Фото верхнего фона', width_field='image_width'),
        ),
    ]
