# Generated by Django 3.0.8 on 2020-11-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201119_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reviewer_name', models.CharField(max_length=255, verbose_name='Имя первого автора')),
                ('first_review', models.CharField(max_length=255, verbose_name='Первый отзыв')),
                ('second_reviewer_name', models.CharField(max_length=255, verbose_name='Имя второго автора')),
                ('second_review', models.CharField(max_length=255, verbose_name='Второй отзыв')),
                ('third_reviewer_name', models.CharField(max_length=255, verbose_name='Имя третьего автора')),
                ('third_review', models.CharField(max_length=255, verbose_name='Третий отзыв')),
                ('fourth_reviewer_name', models.CharField(max_length=255, verbose_name='Имя четвертого автора')),
                ('fourth_review', models.CharField(max_length=255, verbose_name='Четверный отзыв')),
                ('fifth_reviewer_name', models.CharField(max_length=255, verbose_name='Имя пятого автора')),
                ('fifth_review', models.CharField(max_length=255, verbose_name='Пятый отзыв')),
                ('sixth_reviewer_name', models.CharField(max_length=255, verbose_name='Имя шестого автора')),
                ('sixth_review', models.CharField(max_length=255, verbose_name='Шестой отзыв')),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605785023', null=True, verbose_name='id для генерации в шаблоне'),
        ),
    ]
