# Generated by Django 3.0.8 on 2020-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201119_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона в футере')),
                ('email', models.CharField(max_length=255, verbose_name='Email в футере')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес в футере')),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605788398', null=True, verbose_name='id для генерации в шаблоне'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='fourth_review',
            field=models.CharField(max_length=255, verbose_name='Четвертый отзыв'),
        ),
    ]
