# Generated by Django 3.0.8 on 2020-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201119_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605801710', null=True, verbose_name='id для генерации в шаблоне'),
        ),
    ]
