# Generated by Django 3.0.8 on 2020-11-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201119_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='data_product_lid',
            field=models.PositiveIntegerField(blank=True, default='1605864269', null=True, verbose_name='id для генерации в шаблоне'),
        ),
    ]
